(()=>{
let editPath=null,editSha=null,editType=null;
function ensureTools(){const head=document.querySelector('.editor-head');if(!head||document.getElementById('editExistingBtn'))return;const wrap=document.createElement('div');wrap.id='editTools';wrap.style.cssText='grid-column:1/-1;margin:0 0 18px;padding:14px;border:1px solid var(--line);background:#0d090f';wrap.innerHTML='<button type="button" class="button" id="editExistingBtn">Edit Existing</button><div id="existingPicker" style="display:none;margin-top:12px"><label style="display:block;font-size:12px;margin-bottom:6px">Choose an existing entry</label><select id="existingSelect"><option value="">Choose…</option></select><div class="help" id="existingHelp">Loading entries…</div></div>';
head.insertAdjacentElement('afterend',wrap);
document.getElementById('editExistingBtn').onclick=loadList;
}
function resetEdit(){editPath=editSha=null;const b=document.getElementById('editExistingBtn');if(b)b.textContent='Edit Existing';const p=document.getElementById('existingPicker');if(p)p.style.display='none'}
document.addEventListener('click',e=>{const card=e.target.closest&&e.target.closest('.card');if(!card)return;setTimeout(()=>{ensureTools();resetEdit();editType=activeType},0)});
async function loadList(){editType=activeType;const picker=document.getElementById('existingPicker'),sel=document.getElementById('existingSelect'),help=document.getElementById('existingHelp');picker.style.display='block';sel.innerHTML='<option value="">Loading…</option>';help.textContent='Reading Root & Brass…';try{const r=await fetch('/api/crone/entries?type='+encodeURIComponent(editType));const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load entries.');sel.innerHTML='<option value="">Choose…</option>';d.items.forEach(item=>{const o=document.createElement('option');o.value=item.path;o.textContent=(item.plant_group?item.plant_group.replace(/([a-z])([A-Z])/g,'$1 $2')+' · ':'')+item.label;o.dataset.sha=item.sha;sel.appendChild(o)});help.textContent=d.items.length?`${d.items.length} existing entr${d.items.length===1?'y':'ies'}.`:'No existing entries yet.';sel.onchange=()=>sel.value&&openExisting(sel.value)}catch(err){sel.innerHTML='<option value="">Could not load</option>';help.textContent=err.message}}
async function openExisting(path){const help=document.getElementById('existingHelp');help.textContent='Opening entry…';try{const r=await fetch('/api/crone/existing?type='+encodeURIComponent(editType)+'&path='+encodeURIComponent(path));const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not open entry.');editPath=d.path;editSha=d.sha;for(const [name,value] of Object.entries(d.fields||{})){const el=document.getElementById('f-'+name);if(el&&el.type!=='file')el.value=value??''}document.getElementById('editorTitle').textContent='Edit '+schemas[editType].label;document.getElementById('saveButton').textContent='Save Changes';document.getElementById('editExistingBtn').textContent='Editing Existing Entry';help.textContent='Loaded. Change anything below, then tap Save Changes.';document.getElementById('formMessage').textContent='Your existing entry will be updated in place.'}catch(err){help.textContent=err.message}}
async function filePayload2(file){if(!file)return null;return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,data:r.result});r.onerror=reject;r.readAsDataURL(file)})}
document.getElementById('entryForm').addEventListener('submit',async e=>{if(!editPath)return;e.preventDefault();e.stopImmediatePropagation();const saveBtn=document.getElementById('saveButton'),msg=document.getElementById('formMessage');saveBtn.disabled=true;saveBtn.textContent='Saving Changes…';msg.className='form-message';msg.textContent='Updating the existing entry…';try{const fd=new FormData(e.currentTarget),fields={};let image=null;for(const [k,v] of fd.entries()){if(v instanceof File){if(v.size)image=await filePayload2(v)}else fields[k]=v.trim()}const r=await fetch('/api/crone/entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:editType,fields,image,existingPath:editPath,existingSha:editSha})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed.');msg.className='form-message good';msg.textContent=`Updated: ${d.path}`;editSha=null;document.getElementById('existingHelp').textContent='Saved. Reopen this entry before making another edit.'}catch(err){msg.className='form-message error';msg.textContent=err.message||'Crone could not save these changes.'}finally{saveBtn.disabled=false;saveBtn.textContent='Save Changes'}},true);
})();
