(()=>{
  function addStyles(){if(document.getElementById('croneFeatureStyles'))return;const s=document.createElement('style');s.id='croneFeatureStyles';s.textContent=`
    .crone-search{margin:4px 0 30px;padding:18px;border:1px solid var(--line);background:rgba(25,16,28,.78)}
    .crone-search-head{display:flex;justify-content:space-between;align-items:end;gap:14px;margin-bottom:10px}
    .crone-search-head h2{margin:0;color:var(--brass2);font-size:11px;font-weight:normal;letter-spacing:.22em;text-transform:uppercase}
    .crone-search-head span{color:var(--muted);font-size:10px}
    .crone-search-box{position:relative}.crone-search-box input{padding-right:42px}.crone-search-clear{position:absolute;right:3px;top:3px;width:36px;height:36px;border:0;background:transparent;color:var(--muted);font-size:18px}
    .crone-search-results{display:grid;gap:7px;margin-top:10px}.crone-search-result{width:100%;text-align:left;padding:11px 12px;border:1px solid var(--line);background:#0d090f;color:var(--ivory)}
    .crone-search-result:hover,.crone-search-result:focus-visible{border-color:var(--brass);outline:none}.crone-search-result strong{display:block;font-weight:normal;font-size:14px}.crone-search-meta{display:block;color:var(--brass2);font-size:9px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:2px}.crone-search-snippet{display:block;color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .crone-search-state{color:var(--muted);font-size:11px;margin-top:9px}.crone-search-state.error{color:var(--danger)}
    .post-save-actions{display:none;gap:8px;flex-wrap:wrap;margin-top:12px}.post-save-actions.show{display:flex}.post-save-actions .button{min-width:120px}
    @media(max-width:520px){.crone-search{padding:14px}.crone-search-head{align-items:start;flex-direction:column;gap:2px}.post-save-actions{display:none}.post-save-actions.show{display:grid}.post-save-actions .button{width:100%}}
  `;document.head.appendChild(s)}

  function buildSearch(){if(document.getElementById('croneSearch'))return;const status=document.querySelector('.status');if(!status)return;const wrap=document.createElement('section');wrap.id='croneSearch';wrap.className='crone-search';wrap.innerHTML=`<div class="crone-search-head"><h2>Search Root & Brass</h2><span>Find an entry and open it for editing</span></div><div class="crone-search-box"><input id="croneSearchInput" type="search" autocomplete="off" placeholder="Search plants, recipes, journal, grimoire…" aria-label="Search Root and Brass"><button type="button" class="crone-search-clear" id="croneSearchClear" aria-label="Clear search">×</button></div><div class="crone-search-state" id="croneSearchState">Type at least 2 characters.</div><div class="crone-search-results" id="croneSearchResults"></div>`;status.insertAdjacentElement('afterend',wrap);
    const input=document.getElementById('croneSearchInput'),clear=document.getElementById('croneSearchClear');let timer=0,seq=0;
    input.addEventListener('input',()=>{clearTimeout(timer);const q=input.value.trim();if(q.length<2){seq++;render([],q?'Type at least 2 characters.':'');return}timer=setTimeout(()=>runSearch(q,++seq),350)});
    clear.onclick=()=>{input.value='';seq++;render([],'');input.focus()};
  }

  async function runSearch(q,mySeq){const state=document.getElementById('croneSearchState');state.className='crone-search-state';state.textContent='Searching…';try{const r=await fetch('/api/crone/search?q='+encodeURIComponent(q));const d=await r.json();if(mySeq!==window.__croneSearchSeq&&window.__croneSearchSeq!==undefined)return;window.__croneSearchSeq=mySeq;if(!r.ok)throw new Error(d.error||'Search failed.');render(d.items||'',d.items?.length?`${d.items.length} result${d.items.length===1?'':'s'}.`:`No matches for “${q}”.`)}catch(err){state.className='crone-search-state error';state.textContent=err.message||'Crone could not search.'}}

  function render(items,stateText){const out=document.getElementById('croneSearchResults'),state=document.getElementById('croneSearchState');if(!out||!state)return;out.innerHTML='';state.className='crone-search-state';state.textContent=stateText||'';for(const item of (Array.isArray(items)?items:[])){const b=document.createElement('button');b.type='button';b.className='crone-search-result';b.innerHTML=`<span class="crone-search-meta">${escapeHtml(item.typeLabel||item.type)}</span><strong>${escapeHtml(item.label)}</strong>${item.snippet?`<span class="crone-search-snippet">${escapeHtml(item.snippet)}</span>`:''}`;b.onclick=async()=>{state.textContent='Opening '+item.label+'…';try{if(!window.CroneEdit)throw new Error('Edit tools are still loading.');await window.CroneEdit.openFromSearch(item.type,item.path);state.textContent='Opened '+item.label+'.'}catch(err){state.className='crone-search-state error';state.textContent=err.message||'Could not open this entry.'}};out.appendChild(b)}}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

  function buildSaveActions(){const actions=document.querySelector('.form-actions');if(!actions||document.getElementById('postSaveActions'))return;const box=document.createElement('div');box.id='postSaveActions';box.className='post-save-actions';box.innerHTML='<button type="button" class="button primary" id="addAnotherBtn">Add Another</button><button type="button" class="button" id="doneBtn">Done</button>';actions.insertAdjacentElement('afterend',box);document.getElementById('addAnotherBtn').onclick=startAnother;document.getElementById('doneBtn').onclick=()=>{document.getElementById('editorWrap')?.classList.remove('open');box.classList.remove('show');window.scrollTo({top:0,behavior:'smooth'})};const msg=document.getElementById('formMessage');if(msg){new MutationObserver(()=>{if(msg.classList.contains('good')&&(msg.textContent.startsWith('Saved:')||msg.textContent.startsWith('Updated:'))){box.classList.add('show')}}).observe(msg,{childList:true,characterData:true,subtree:true,attributes:true})}}

  function startAnother(){const box=document.getElementById('postSaveActions');box?.classList.remove('show');const type=typeof activeType!=='undefined'?activeType:null;if(!type)return;const label=schemas[type]?.label;const card=[...document.querySelectorAll('.card')].find(b=>b.querySelector('strong')?.textContent===label);if(card)card.click();else if(typeof openEditor==='function')openEditor(type);setTimeout(()=>{const form=document.getElementById('entryForm');form?.reset();schemas[type]?.fields?.forEach(f=>{if(f[4]){const el=document.getElementById('f-'+f[0]);if(el)el.value=typeof f[4]==='function'?f[4]():f[4]}});window.CroneEdit?.reset?.();const msg=document.getElementById('formMessage');if(msg){msg.className='form-message';msg.textContent='Nothing is saved until you tap Save.'}document.getElementById('editorTitle').textContent='New '+schemas[type].label;document.getElementById('editorWrap')?.scrollIntoView({behavior:'smooth',block:'start'})},80)}

  addStyles();buildSearch();buildSaveActions();
})();
