defaults:
  - scope:
      path: "grimoire/dreams/entries"
      type: "pages"
    values:
      layout: dream

  - scope:
      path: "grimoire/spells/entries"
      type: "pages"
    values:
      layout: spell

  - scope:
      path: "grimoire/recipes/entries"
      type: "pages"
    values:
      layout: recipe

  - scope:
      path: "grimoire/tarot/entries"
      type: "pages"
    values:
      layout: tarot

  - scope:
      path: "grimoire/moon/entries"
      type: "pages"
    values:
      layout: moon

  - scope:
      path: "grimoire/crystals/entries"
      type: "pages"
    values:
      layout: crystal

  - scope:
      path: "journal/entries"
      type: "pages"
    values:
      layout: journal
