defaults:
  - scope:
      path: "grimoire/dreams/entries"
      type: "pages"
    values:
      layout: dream

  - scope:
      path: "grimoire/spells/entries"
      type: "pages"
    values:
      layout: spell

  - scope:
      path: "grimoire/recipes/entries"
      type: "pages"
    values:
      layout: recipe

  - scope:
      path: "grimoire/tarot/entries"
      type: "pages"
    values:
      layout: tarot
