defaults:
  - scope:
      path: "grimoire/dreams/entries"
      type: "pages"
    values:
      layout: dream

  - scope:
      path: "grimoire/spells/entries"
      type: "pages"
    values:
      layout: spell

  - scope:
      path: "grimoire/recipes/entries"
      type: "pages"
    values:
      layout: recipe

  - scope:
      path: "grimoire/tarot/entries"
      type: "pages"
    values:
      layout: tarot

  - scope:
      path: "grimoire/moon/entries"
      type: "pages"
    values:
      layout: moon

  - scope:
      path: "grimoire/crystals/entries"
      type: "pages"
    values:
      layout: crystal

  - scope:
      path: "grimoire/signs-symbols/entries"
      type: "pages"
    values:
      layout: symbol

  - scope:
      path: "grimoire/apothecary/entries"
      type: "pages"
    values:
      layout: apothecary

  - scope:
      path: "journal/entries"
      type: "pages"
    values:
      layout: journal

  - scope:
      path: "kitchen/entries"
      type: "pages"
    values:
      layout: kitchen

  - scope:
      path: "garden/plants/treesandshrubs"
      type: "pages"
    values:
      layout: plant
      plant_group: trees-shrubs

  - scope:
      path: "garden/plants/flowers"
      type: "pages"
    values:
      layout: plant
      plant_group: flowers

  - scope:
      path: "garden/plants/climbers"
      type: "pages"
    values:
      layout: plant
      plant_group: climbers

  - scope:
      path: "garden/plants/edibles"
      type: "pages"
    values:
      layout: plant
      plant_group: edibles
